//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Authors")
export class AuthorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Authorname: string;

@Column({nullable: true})
Dateofbirth: string;

@Column({nullable: true})
Gender: string;

@Column({nullable: true})
Id: string;


}
