//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Books")
export class BooksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Booktitle: string;

@Column({nullable: true})
Releasedate: string;

@Column({nullable: true})
Authorname: string;

@Column({nullable: true})
Id: string;


}
